Repository gdsc-abesit/GDSC-ABESIT, pull requests merged in 2023-10, with the labels that each got.

#22 minor fixes
  components/Contact.jsx
  components/Contributors.jsx
  components/Navbar.jsx
  components/Team.jsx
  pages/index.js
  pages/team.js
  public/favicon.ico
Labels: hacktoberfest, hacktoberfest-accepted

#57 #Fixes 51 : Add Responsive Navbar
  components/Navbar.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#59 Add About section
  .vscode/settings.json
  components/About.jsx
  components/PreviousEvents.jsx
  package-lock.json
  package.json
  pages/index.js
Labels: hacktoberfest, hacktoberfest-accepted

#58 added darkmode with next-themes
  components/Contact.jsx
  components/Contributors.jsx
  components/Footer.jsx
  components/Hero.jsx
  components/Navbar.jsx
  components/PreviousEvents.jsx
  components/Team.jsx
  components/ThemeButton.jsx
  pages/_app.js
  pages/index.js
  styles/globals.css
  tailwind.config.js
Labels: hacktoberfest

#69 update readme file
  README.md
Labels: hacktoberfest-accepted

#71 Changed the colour of GDSC Heading
  components/Hero.jsx
Labels: hacktoberfest

#80 #77 Fix. Contact Us Page
  components/Contact.jsx
Labels: hacktoberfest

#85 Improved the responsiveness of team page
  components/Team.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#82 Load More Button And Added Generic Images
  assets/GenericUserImage/01.png
  assets/GenericUserImage/02.png
  assets/GenericUserImage/03.png
  assets/GenericUserImage/04.png
  assets/GenericUserImage/05.png
  components/Contributors.jsx
  package-lock.json
Labels: hacktoberfest

#95 Changed logo and added abbreviation besides it
  components/Navbar.jsx
Labels: hacktoberfest

#96 Fix. Team Page UI for tablet devices
  .talismanrc
  components/Team.jsx
Labels: hacktoberfest

#94 Created ContributorData file
  ContributorData/contributorData.js
  components/Contributors.jsx
Labels: hacktoberfest

#97 Fixed the responsiveness of contributor page
  components/Contributors.jsx
Labels: hacktoberfest

#105 Update contributorData.js
  ContributorData/contributorData.js
Labels: hacktoberfest
